## Site Meta ##
# The title of the website.
title: "Henri Antikainen"
# The description of the website
description: "Photography"
# Keywords/tags for you site.
keywords: "photography, New Jersey"
# Your copyright message.
copyright: "Copyright &copy; 2021 - Henri Antikainen."

## Site Configurations ##
# 1st heading of the site.
header: "Henri Antikainen"
# 2nd heading/sub heading of the website.
subheader: ""
# A description/bio of the website.
bio: "Photography"
social:
  # Your Twitter username.
  twitter_username: ""
  # Your Facebook username.
  facebook_username: ""
  # Your Instagram username.
  instagram_username: "antihenri"
  # GitHub username.
  github_username: ""
  # Your email address.
  email: ""

## Gallery Configuration ##
# If you modify this, also modify the `default.scope.path` key below.
gallery_dir: "gallery"
# Any valid value of "background-position" CSS attribute.
image_position: "left center"

## Jekyll Configuration ##
defaults:
 - scope:
    # Should be same as the `gallery_dir` key above.
    path: "gallery"
   values:
    image: true
